#!/bin/sh
 
INPUT=$1
OUTPUT=$2
 
mplayer "$INPUT" -ao pcm:fast:file=audio.wav -vc null -vo null -nocorrect-pts
mencoder "$INPUT" \
    -ffourcc divx \
    -ovc lavc -lavcopts vcodec=mpeg4:vhq \
    -audiofile audio.wav \
    -oac mp3lame -lameopts vbr=3 \
    -slang eng \
    -o "$OUTPUT"
 
rm -f audio.wav
